#!/usr/bin/env bash
set -eu

file=$1
w=$2
h=$3
x=$4
y=$5


if [[ "$(file -Lb --mime-type "$1")" =~ ^image/png ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"  < /dev/null > /dev/tty
    exit 1
fi


filename=$(basename $(echo "$file" | tr ' ' '_'))
if [[ "$(file -Lb --mime-type "$file")" =~ ^application/pdf ]]; then
    echo "GOT a pdf";
    if [[ ! -f "/tmp/$filename.png" ]]; then
        pdftoppm -f 1 -l 1 "$file" >> "/tmp/$filename.png"
    fi

    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "/tmp/$filename.png" < /dev/null > /dev/tty
	exit 1
fi




pistol "$file"
